version: "3.9"

services:
  db:
    networks:
      - wordpressnetwork
    image: mysql:5.7
    volumes:
      - ./${DATA_DIR}/db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    networks:
      - wordpressnetwork
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./${DATA_DIR}/wordpress-data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  reverse-proxy:
    networks:
      - wordpressnetwork
    image: nginx
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    container_name: nginx-proxy
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - wordpress
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  wordpressnetwork:
    driver: bridge
